# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: entities.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='entities.proto',
  package='workshop',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0e\x65ntities.proto\x12\x08workshop\x1a\x1fgoogle/protobuf/timestamp.proto\"\x1f\n\x0c\x43onfirmFraud\x12\x0f\n\x07\x61\x63\x63ount\x18\x01 \x01(\t\"o\n\x0bTransaction\x12\x0f\n\x07\x61\x63\x63ount\x18\x01 \x01(\t\x12-\n\ttimestamp\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x10\n\x08merchant\x18\x03 \x01(\t\x12\x0e\n\x06\x61mount\x18\x04 \x01(\x05\"L\n\rFeatureVector\x12\x13\n\x0b\x66raud_count\x18\x01 \x01(\x05\x12\x16\n\x0emerchant_score\x18\x02 \x01(\x05\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x05\"\x1b\n\nFraudScore\x12\r\n\x05score\x18\x01 \x01(\x05\"\x1e\n\rReportedFraud\x12\r\n\x05\x63ount\x18\x01 \x01(\x05\"\r\n\x0b\x45xpireFraud\"\x0c\n\nQueryFraud\"\x1e\n\rMerchantScore\x12\r\n\x05score\x18\x01 \x01(\x05\"\x14\n\x12QueryMerchantScore\"\x15\n\x13\x45xpireMerchantScore\"5\n\x0f\x43ustomThreshold\x12\x11\n\tthreshold\x18\x01 \x01(\x05\x12\x0f\n\x07\x61\x63\x63ount\x18\x02 \x01(\t\"\x10\n\x0eQueryThresholdb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_CONFIRMFRAUD = _descriptor.Descriptor(
  name='ConfirmFraud',
  full_name='workshop.ConfirmFraud',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='account', full_name='workshop.ConfirmFraud.account', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=61,
  serialized_end=92,
)


_TRANSACTION = _descriptor.Descriptor(
  name='Transaction',
  full_name='workshop.Transaction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='account', full_name='workshop.Transaction.account', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='workshop.Transaction.timestamp', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='merchant', full_name='workshop.Transaction.merchant', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='amount', full_name='workshop.Transaction.amount', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=94,
  serialized_end=205,
)


_FEATUREVECTOR = _descriptor.Descriptor(
  name='FeatureVector',
  full_name='workshop.FeatureVector',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='fraud_count', full_name='workshop.FeatureVector.fraud_count', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='merchant_score', full_name='workshop.FeatureVector.merchant_score', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='amount', full_name='workshop.FeatureVector.amount', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=207,
  serialized_end=283,
)


_FRAUDSCORE = _descriptor.Descriptor(
  name='FraudScore',
  full_name='workshop.FraudScore',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='score', full_name='workshop.FraudScore.score', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=285,
  serialized_end=312,
)


_REPORTEDFRAUD = _descriptor.Descriptor(
  name='ReportedFraud',
  full_name='workshop.ReportedFraud',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='count', full_name='workshop.ReportedFraud.count', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=314,
  serialized_end=344,
)


_EXPIREFRAUD = _descriptor.Descriptor(
  name='ExpireFraud',
  full_name='workshop.ExpireFraud',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=346,
  serialized_end=359,
)


_QUERYFRAUD = _descriptor.Descriptor(
  name='QueryFraud',
  full_name='workshop.QueryFraud',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=361,
  serialized_end=373,
)


_MERCHANTSCORE = _descriptor.Descriptor(
  name='MerchantScore',
  full_name='workshop.MerchantScore',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='score', full_name='workshop.MerchantScore.score', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=375,
  serialized_end=405,
)


_QUERYMERCHANTSCORE = _descriptor.Descriptor(
  name='QueryMerchantScore',
  full_name='workshop.QueryMerchantScore',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=407,
  serialized_end=427,
)


_EXPIREMERCHANTSCORE = _descriptor.Descriptor(
  name='ExpireMerchantScore',
  full_name='workshop.ExpireMerchantScore',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=429,
  serialized_end=450,
)


_CUSTOMTHRESHOLD = _descriptor.Descriptor(
  name='CustomThreshold',
  full_name='workshop.CustomThreshold',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='threshold', full_name='workshop.CustomThreshold.threshold', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='account', full_name='workshop.CustomThreshold.account', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=452,
  serialized_end=505,
)


_QUERYTHRESHOLD = _descriptor.Descriptor(
  name='QueryThreshold',
  full_name='workshop.QueryThreshold',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=507,
  serialized_end=523,
)

_TRANSACTION.fields_by_name['timestamp'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
DESCRIPTOR.message_types_by_name['ConfirmFraud'] = _CONFIRMFRAUD
DESCRIPTOR.message_types_by_name['Transaction'] = _TRANSACTION
DESCRIPTOR.message_types_by_name['FeatureVector'] = _FEATUREVECTOR
DESCRIPTOR.message_types_by_name['FraudScore'] = _FRAUDSCORE
DESCRIPTOR.message_types_by_name['ReportedFraud'] = _REPORTEDFRAUD
DESCRIPTOR.message_types_by_name['ExpireFraud'] = _EXPIREFRAUD
DESCRIPTOR.message_types_by_name['QueryFraud'] = _QUERYFRAUD
DESCRIPTOR.message_types_by_name['MerchantScore'] = _MERCHANTSCORE
DESCRIPTOR.message_types_by_name['QueryMerchantScore'] = _QUERYMERCHANTSCORE
DESCRIPTOR.message_types_by_name['ExpireMerchantScore'] = _EXPIREMERCHANTSCORE
DESCRIPTOR.message_types_by_name['CustomThreshold'] = _CUSTOMTHRESHOLD
DESCRIPTOR.message_types_by_name['QueryThreshold'] = _QUERYTHRESHOLD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ConfirmFraud = _reflection.GeneratedProtocolMessageType('ConfirmFraud', (_message.Message,), {
  'DESCRIPTOR' : _CONFIRMFRAUD,
  '__module__' : 'entities_pb2'
  # @@protoc_insertion_point(class_scope:workshop.ConfirmFraud)
  })
_sym_db.RegisterMessage(ConfirmFraud)

Transaction = _reflection.GeneratedProtocolMessageType('Transaction', (_message.Message,), {
  'DESCRIPTOR' : _TRANSACTION,
  '__module__' : 'entities_pb2'
  # @@protoc_insertion_point(class_scope:workshop.Transaction)
  })
_sym_db.RegisterMessage(Transaction)

FeatureVector = _reflection.GeneratedProtocolMessageType('FeatureVector', (_message.Message,), {
  'DESCRIPTOR' : _FEATUREVECTOR,
  '__module__' : 'entities_pb2'
  # @@protoc_insertion_point(class_scope:workshop.FeatureVector)
  })
_sym_db.RegisterMessage(FeatureVector)

FraudScore = _reflection.GeneratedProtocolMessageType('FraudScore', (_message.Message,), {
  'DESCRIPTOR' : _FRAUDSCORE,
  '__module__' : 'entities_pb2'
  # @@protoc_insertion_point(class_scope:workshop.FraudScore)
  })
_sym_db.RegisterMessage(FraudScore)

ReportedFraud = _reflection.GeneratedProtocolMessageType('ReportedFraud', (_message.Message,), {
  'DESCRIPTOR' : _REPORTEDFRAUD,
  '__module__' : 'entities_pb2'
  # @@protoc_insertion_point(class_scope:workshop.ReportedFraud)
  })
_sym_db.RegisterMessage(ReportedFraud)

ExpireFraud = _reflection.GeneratedProtocolMessageType('ExpireFraud', (_message.Message,), {
  'DESCRIPTOR' : _EXPIREFRAUD,
  '__module__' : 'entities_pb2'
  # @@protoc_insertion_point(class_scope:workshop.ExpireFraud)
  })
_sym_db.RegisterMessage(ExpireFraud)

QueryFraud = _reflection.GeneratedProtocolMessageType('QueryFraud', (_message.Message,), {
  'DESCRIPTOR' : _QUERYFRAUD,
  '__module__' : 'entities_pb2'
  # @@protoc_insertion_point(class_scope:workshop.QueryFraud)
  })
_sym_db.RegisterMessage(QueryFraud)

MerchantScore = _reflection.GeneratedProtocolMessageType('MerchantScore', (_message.Message,), {
  'DESCRIPTOR' : _MERCHANTSCORE,
  '__module__' : 'entities_pb2'
  # @@protoc_insertion_point(class_scope:workshop.MerchantScore)
  })
_sym_db.RegisterMessage(MerchantScore)

QueryMerchantScore = _reflection.GeneratedProtocolMessageType('QueryMerchantScore', (_message.Message,), {
  'DESCRIPTOR' : _QUERYMERCHANTSCORE,
  '__module__' : 'entities_pb2'
  # @@protoc_insertion_point(class_scope:workshop.QueryMerchantScore)
  })
_sym_db.RegisterMessage(QueryMerchantScore)

ExpireMerchantScore = _reflection.GeneratedProtocolMessageType('ExpireMerchantScore', (_message.Message,), {
  'DESCRIPTOR' : _EXPIREMERCHANTSCORE,
  '__module__' : 'entities_pb2'
  # @@protoc_insertion_point(class_scope:workshop.ExpireMerchantScore)
  })
_sym_db.RegisterMessage(ExpireMerchantScore)

CustomThreshold = _reflection.GeneratedProtocolMessageType('CustomThreshold', (_message.Message,), {
  'DESCRIPTOR' : _CUSTOMTHRESHOLD,
  '__module__' : 'entities_pb2'
  # @@protoc_insertion_point(class_scope:workshop.CustomThreshold)
  })
_sym_db.RegisterMessage(CustomThreshold)

QueryThreshold = _reflection.GeneratedProtocolMessageType('QueryThreshold', (_message.Message,), {
  'DESCRIPTOR' : _QUERYTHRESHOLD,
  '__module__' : 'entities_pb2'
  # @@protoc_insertion_point(class_scope:workshop.QueryThreshold)
  })
_sym_db.RegisterMessage(QueryThreshold)


# @@protoc_insertion_point(module_scope)
