apiVersion: v1
kind: Service
metadata:
  name: transaction-manager 
spec:
  type: ClusterIP
  ports:
    - name: endpoint
      port: 8100
  selector:
    app: transaction-manager
    component: functions 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transaction-manager
      component: functions
  template:
    metadata:
      labels:
        app: transaction-manager
        component: functions
    spec:
      containers:
        - name: transaction-manager 
          image: us.gcr.io/da-fe-212612/transaction-manager:v1 
          # imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8100
              name: endpoint
          livenessProbe:
            tcpSocket:
              port: 8100
            initialDelaySeconds: 30
            periodSeconds: 60
