apiVersion: v1
kind: ConfigMap
metadata:
  name: gw-nginx-conf
data:
  nginx.conf: |
    events {}
    http {
        server {
            listen 80 default_server;
            server_name _;

            location /transaction-manager {
              proxy_pass http://transaction-manager:8100/statefun;
            }

            location /counter {
              proxy_pass http://transaction-manager:8100/statefun;
            }

            location /model {
              proxy_pass http://model:8900/statefun;
            }
        }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - image: nginx
          imagePullPolicy: IfNotPresent
          name: nginx
          ports:
            - containerPort: 80
              name: http
          volumeMounts:
            - mountPath: /etc/nginx
              name: gw-nginx-conf
      volumes:
        - configMap:
            name: gw-nginx-conf
          name: gw-nginx-conf
---
apiVersion: v1
kind: Service
metadata:
  name: functions
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: nginx
  type: LoadBalancer